### ISSUE TITLE
Filter by Minecraft Version not working

### ISSUE THREAD

**Issue by lyssar** [kleister/go-forge#21]
Hello,
thank you for your time developing this package. It helps a lot :) 
I think I found a little bug in your filter logic. If you try filtering only by a Minecraft Version Contraint than your result will be always empty.

Example:
```golang

forge, _ := version.FromDefault()
f := &version.Filter{
	Minecraft: "1.16.5",
}

for _, version := range forge.Releases.Filter(f) {
	fmt.Println(version.Minecraft)
}
```

The result will be empty.
I think the issue is at `versions.go:30` where you check and apply the filter of the Minecraft version. you are using `row.ID` but I am pretty sure it must be `row.Minecraft` in this case?`

Would be nice if you can take a look or if you need helpt I can provide a PR for you :) 

Thanks!

**Comment by tboerger** [comment]
Thanks for the report, and you are right. I have published v1.0.1 to resolve the issue. Let's see that I will add a proper pipeline and automated dependency updates soon :)
